#!/usr/bin/env python3
"""Convert the R2D3 URDF to USD using urdf_usd_converter (Isaac Sim 6.0+).

This is a thin wrapper around the `urdf_usd_converter` CLI shipped with
isaacsim 6.0.0.0. The converter is a pure-Python tool from NVIDIA's Newton
team — it does NOT need to bootstrap SimulationApp / Kit, so this script
runs against the standalone `isaac` conda env directly.

Usage examples
--------------

  # Convert the V1 wrapper URDF (renders 75b + D435 + parallel grippers).
  # NOTE: r2d3_v1.urdf is generated by `isaac_sim/urdf/render.sh` first.
  scripts/urdf_to_usd.py

  # Convert the bare upstream 75b URDF (no grippers, no D435 — quick sanity).
  scripts/urdf_to_usd.py --urdf ros2_rm_robot/dual_rm_description/dual_rm_75b_description/urdf/dual_rm_75b_description.urdf

  # Override output location.
  scripts/urdf_to_usd.py --usd-dir /tmp/usd_out

The script auto-discovers `package://<pkg>/...` references in the URDF and
maps each `<pkg>` to its directory under `ros2_rm_robot/dual_rm_description/`
or `ros2_realsense2/realsense2_description/`. Missing packages are reported
and the conversion is aborted before invoking the converter.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Where to find the isaac env's Python (the converter is a pip-installed module
# living in that env). Honor R2D3_ISAAC_PY first, then common install locations,
# then $PATH — so this isn't tied to one machine.
ISAAC_PY = None
for _cand in (
    os.environ.get("R2D3_ISAAC_PY"),
    str(Path.home() / "miniforge3" / "envs" / "isaac" / "bin" / "python"),
    str(Path.home() / "mambaforge" / "envs" / "isaac" / "bin" / "python"),
    str(Path.home() / "miniconda3" / "envs" / "isaac" / "bin" / "python"),
):
    if _cand and Path(_cand).is_file():
        ISAAC_PY = Path(_cand)
        break
if ISAAC_PY is None:
    ISAAC_PY = Path(shutil.which("python") or "python")

# Default V1 wrapper (rendered output of isaac_sim/urdf/render.sh).
DEFAULT_URDF = REPO_ROOT / "isaac_sim/urdf/r2d3_v1.urdf"
# Fallback if the wrapper isn't rendered yet — bare upstream URDF.
FALLBACK_URDF = (
    REPO_ROOT
    / "ros2_rm_robot/dual_rm_description/dual_rm_75b_description"
    / "urdf/dual_rm_75b_description.urdf"
)
DEFAULT_USD_DIR = REPO_ROOT / "isaac_sim/usd"

# Known package locations in this repo. Add new ones here as we compose more URDFs.
PACKAGE_DIRS = {
    "dual_rm_75b_description":
        REPO_ROOT / "ros2_rm_robot/dual_rm_description/dual_rm_75b_description",
    "dual_rm_65b_description":
        REPO_ROOT / "ros2_rm_robot/dual_rm_description/dual_rm_65b_description",
    "realsense2_description":
        REPO_ROOT / "ros2_realsense2/realsense2_description",
}


def discover_packages(urdf_path: Path) -> list[tuple[str, Path]]:
    """Scan URDF for package:// references; return list of (pkg, abs_path)."""
    pkg_pattern = re.compile(r'package://([A-Za-z_][A-Za-z0-9_]*)/')
    text = urdf_path.read_text()
    pkgs = sorted(set(pkg_pattern.findall(text)))
    out = []
    missing = []
    for pkg in pkgs:
        loc = PACKAGE_DIRS.get(pkg)
        if loc and loc.is_dir():
            out.append((pkg, loc))
        else:
            missing.append(pkg)
    if missing:
        print(
            f"error: URDF references {len(missing)} package(s) we can't map: "
            f"{missing}. Add them to PACKAGE_DIRS in {__file__}.",
            file=sys.stderr,
        )
        sys.exit(1)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--urdf", type=Path, default=DEFAULT_URDF)
    parser.add_argument("--usd-dir", type=Path, default=DEFAULT_USD_DIR)
    parser.add_argument(
        "--no-layer-structure",
        action="store_true",
        help="Produce a single USDC layer instead of the Atomic Component structure (see converter --help).",
    )
    parser.add_argument(
        "--no-physics-scene",
        action="store_true",
        help="Skip authoring the UsdPhysics.Scene prim (useful for visual-only assets).",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Pass through to the converter.",
    )
    parser.add_argument(
        "--comment", "-c",
        default="R2D3 V1 — generated by scripts/urdf_to_usd.py",
    )
    args = parser.parse_args()

    # URDF discovery / fallback
    if not args.urdf.is_file():
        if args.urdf == DEFAULT_URDF and FALLBACK_URDF.is_file():
            print(
                f"warn: {args.urdf} not rendered yet; falling back to bare 75b URDF "
                f"({FALLBACK_URDF}). Gripper and D435 will be MISSING from the USD.",
                file=sys.stderr,
            )
            args.urdf = FALLBACK_URDF
        else:
            print(f"error: URDF not found: {args.urdf}", file=sys.stderr)
            return 1
    args.usd_dir.mkdir(parents=True, exist_ok=True)

    # Build the converter invocation
    pkgs = discover_packages(args.urdf)
    cmd = [str(ISAAC_PY), "-m", "urdf_usd_converter",
           str(args.urdf), str(args.usd_dir),
           "--comment", args.comment]
    if args.no_layer_structure:
        cmd.append("--no-layer-structure")
    if args.no_physics_scene:
        cmd.append("--no-physics-scene")
    if args.verbose:
        cmd.append("--verbose")
    for pkg, loc in pkgs:
        cmd.extend(["--package", f"{pkg}={loc}"])

    # EULA acceptance — set even though urdf_usd_converter is pure Python,
    # in case any sub-import triggers Kit bootstrap.
    env = os.environ.copy()
    env["OMNI_KIT_ACCEPT_EULA"] = "YES"
    env["PRIVACY_CONSENT"] = "Y"
    env["ACCEPT_EULA"] = "Y"

    print(f"[urdf_to_usd] urdf:        {args.urdf}")
    print(f"[urdf_to_usd] usd_dir:     {args.usd_dir}")
    print(f"[urdf_to_usd] packages:    {[p for p, _ in pkgs]}")
    print(f"[urdf_to_usd] invoking:    {' '.join(cmd)}")
    print()

    return subprocess.call(cmd, env=env)


if __name__ == "__main__":
    raise SystemExit(main())
