# Default initial positions for dual_rm_65b_description's ros2_control fake system

initial_positions:
  l_joint1: 0
  l_joint2: 0
  l_joint3: 0
  l_joint4: 0
  l_joint5: 0
  l_joint6: 0
  platform_joint: 0
  r_joint1: 0
  r_joint2: 0
  r_joint3: 0
  r_joint4: 0
  r_joint5: 0
  r_joint6: 0
  left_thumb_proximal_yaw_joint: 0
  left_thumb_proximal_pitch_joint: 0
  left_thumb_intermediate_joint: 0
  left_thumb_distal_joint: 0
  left_index_proximal_joint: 0
  left_index_intermediate_joint: 0
  left_middle_proximal_joint: 0
  left_middle_intermediate_joint: 0
  left_ring_proximal_joint: 0
  left_ring_intermediate_joint: 0
  left_pinky_proximal_joint: 0
  left_pinky_intermediate_joint: 0
  right_thumb_proximal_yaw_joint: 0
  right_thumb_proximal_pitch_joint: 0
  right_thumb_intermediate_joint: 0
  right_thumb_distal_joint: 0
  right_index_proximal_joint: 0
  right_index_intermediate_joint: 0
  right_middle_proximal_joint: 0
  right_middle_intermediate_joint: 0
  right_ring_proximal_joint: 0
  right_ring_intermediate_joint: 0
  right_pinky_proximal_joint: 0
  right_pinky_intermediate_joint: 0